### ISSUE TITLE
Add deep links

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl-docs#36]
`https://docs.driftctl.com/ci_cd` => `https://docs.driftctl.com/{LATEST}/ci_cd/intro`
`https://docs.driftctl.com/limitations` => `https://docs.driftctl.com/{LATEST}/limitations`
`https://docs.driftctl.com/aws/policy` => `https://docs.driftctl.com/{LATEST}/providers/aws/authentication#least-privileged-policy`

If we cannot redirect to the anchor, redirect to the page

**Comment by wbeuil** [comment]
I succeeded to create a deep link redirection for EACH `/<LATEST>/<EXACT_PATH>` in an automatic way besides custom ones like `/ci_cd` redirects to `/<LATEST>/ci_cd/intro`, but I need to hack on the one with an anchor link.

What I mean by hack on this one is I need to create a `aws/policy.js` file inside our pages that its sole purpose is to redirect to our anchor link. The plugin to redirects with Docusaurus won't let us use anchor link the url path...

Anyway if you're okay with that I push my branch.
