### ISSUE TITLE
GPG verification doesn't verify checksums

### ISSUE THREAD

**Issue by paulhammond** [cloudskiff/driftctl-docs#70]
It looks like the instructions for verifying downloads don't actually verify the checksum file is correctly signed. Here's a lightly edited output from a terminal session:

```
# I could put anything in this file
$ echo "hello" > driftctl_SHA256SUMS

# but running the verification step from the docs says the signature is fine:
$ gpg --verify driftctl_SHA256SUMS.gpg
gpg: Signature made Tue 08 Jun 2021 09:09:59 AM PDT
gpg:                using EDDSA key 277666005A7F01D484F6376DACC776A79C824EBD
gpg:                issuer "security@cloudskiff.com"
gpg: Good signature from "Cloudskiff <security@cloudskiff.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2776 6600 5A7F 01D4 84F6  376D ACC7 76A7 9C82 4EBD
```

As a result you can't really trust the checksums file used in the next step. I think you either want to use a detached signature, or extract the checksums from the attached signature (using `gpg --output driftctl_SHA256SUMS --decrypt driftctl_SHA256SUMS.gpg`) instead of downloading them directly? But it's also possible I've made a mistake here?

**Comment by eliecharra** [comment]
Hi @paulhammond thanks for your report. There is an issue with the detached sign (which is not generated as a detached sig)

This will be fixed for the next upcoming `0.10.0` release with https://github.com/cloudskiff/driftctl/commit/03b12088531b791b549afb9b2e4f9dbe86b8a5b0 and https://github.com/cloudskiff/driftctl-docs/commit/1d011c4ed8dea58a7220c623d9a56dd36c9d60a7

ping @wbeuil maybe you'll have to update dctlenv

**Comment by wbeuil** [comment]
Will modify ASAP dctlenv !

**Comment by sjourdan** [comment]
note to self => wait for 0.10 release & check again

**Comment by sjourdan** [comment]
LGTM! 

```
❯  gpg --verify driftctl_SHA256SUMS.gpg driftctl_SHA256SUMS
gpg: Signature made Tue 22 Jun 2021 05:24:16 PM CEST
gpg:                using EDDSA key 277666005A7F01D484F6376DACC776A79C824EBD
gpg:                issuer "security@cloudskiff.com"
gpg: Good signature from "Cloudskiff <security@cloudskiff.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2776 6600 5A7F 01D4 84F6  376D ACC7 76A7 9C82 4EBD

```

```
❯  echo "hello" >> driftctl_SHA256SUMS
❯  gpg --verify driftctl_SHA256SUMS.gpg driftctl_SHA256SUMS
gpg: Signature made Tue 22 Jun 2021 05:24:16 PM CEST
gpg:                using EDDSA key 277666005A7F01D484F6376DACC776A79C824EBD
gpg:                issuer "security@cloudskiff.com"
gpg: BAD signature from "Cloudskiff <security@cloudskiff.com>" [unknown]
```
